### PR TITLE
Cleanup SDK Java for V3

### PR DESCRIPTION
**Pull request by Shiranuit**
## What does this PR do ?
Prepare a clean branch for the Java SDK V3

### CODE REVIEW

**Comment by Aschen** [comment]
Considering the high level of changed file, can you tell us what kind of cleaning have you made ?

**Comment by Shiranuit** [comment]
I have removed every sources and tests

**Comment by scottinet** [comment]
Did you migrate the documentation?

**Comment by Shiranuit** [comment]
> Did you migrate the documentation?

No I deleted it

**Pull request merged**
